export const ADD_PRODUCTS_TO_WISHLIST = "ADD_PRODUCTS_TO_WISHLIST";
export const ADD_PRODUCTS_TO_WISHLIST_SUCCESS =
  "ADD_PRODUCTS_TO_WISHLIST_SUCCESS";
export const ADD_PRODUCTS_TO_WISHLIST_FAILED =
  "ADD_PRODUCTS_TO_WISHLIST_FAILED";
export const FETCH_PRODUCTS_FROM_WISHLIST = "FETCH_PRODUCTS_FROM_WISHLIST";
export const FETCH_PRODUCTS_FROM_WISHLIST_SUCCESS =
  "FETCH_PRODUCTS_FROM_WISHLIST_SUCCESS";
export const FETCH_PRODUCTS_FROM_WISHLIST_FAILED =
  "FETCH_PRODUCTS_FROM_WISHLIST_FAILED";
export const REMOVE_PRODUCT_FROM_WISHLIST = "REMOVE_PRODUCT_FROM_WISHLIST";
export const REMOVE_PRODUCT_FROM_WISHLIST_SUCCESS =
  "REMOVE_PRODUCT_FROM_WISHLIST_SUCCESS";
export const REMOVE_PRODUCT_FROM_WISHLIST_FAILED =
  "REMOVE_PRODUCT_FROM_WISHLIST_FAILED";

// export const UPDATE_CART_PRODUCT = "UPDATE_CART_PRODUCT";
// export const UPDATE_CART_PRODUCT_SUCCESS = "UPDATE_CART_PRODUCT_SUCCESS";
// export const UPDATE_CART_PRODUCT_FAILED = "UPDATE_CART_PRODUCT_FAILED";
// export const ADD_COUPON = "ADD_COUPON";
// export const REMOVE_COUPON = "REMOVE_COUPON";
// export const COUPON_FAILURE = "COUPON_FAILURE";
