import Img1 from "../../../public/assets/productCardImg/product-card.png";
import Img2 from "../../../public/assets/productCardImg/product-card2.png";
import Img3 from "../../../public/assets/productCardImg/product-card3.png";
import Img4 from "../../../public/assets/productCardImg/product-card4.png";
//
export const productCardData = {
  label1: "Most Popular Products",
  label2: "See all",
  data: [
    {
      id: 1,
      imgs: [Img1, Img1, Img2],
      title: "Casual Sneakers Canvas Shoes For Sneakers For Men",
      rating: 4.5,
      actual_price: "₹700",
      discount_price: "₹350",
      off_percentage: "(50% off)",
      product_status: "In Stock",
    },
    {
      id: 2,
      imgs: [Img2],
      title: "Fit-Man Slip On Sneakers For Men  -Red, Black",
      rating: 3,
      actual_price: "₹700",
      discount_price: "₹350",
      product_status: "In Stock",
    },
    {
      id: 3,
      imgs: [Img3],
      title: "Sneakers Sneakers For Men  -Black, White",
      rating: 3.5,
      actual_price: "₹700",
      discount_price: "₹350",
      off_percentage: "(50% off)",
      product_status: "In Stock",
    },
    {
      id: 4,
      imgs: [Img4],
      title: "Mesh Lightweighted Sports, Casual, Outdoor, Model.",
      rating: 2,
      actual_price: "₹700",
      discount_price: "₹350",
      off_percentage: "(50% off)",
      product_status: "In Stock",
    },
    {
      id: 4,
      imgs: [Img3],
      title: "Mesh Lightweighted Sports, Casual, Outdoor, Model.",
      rating: 2,
      actual_price: "₹700",
      discount_price: "₹350",
      off_percentage: "(50% off)",
      product_status: "In Stock",
    },
    {
      id: 4,
      imgs: [Img1, Img1, Img2],
      title: "Mesh Lightweighted Sports, Casual, Outdoor, Model.",
      rating: 2,
      actual_price: "₹700",
      discount_price: "₹350",
      off_percentage: "(50% off)",
      product_status: "In Stock",
    },
    {
      id: 4,
      imgs: [Img4],
      title: "Mesh Lightweighted Sports, Casual, Outdoor, Model.",
      rating: 2,
      actual_price: "₹700",
      discount_price: "₹350",
      off_percentage: "(50% off)",
      product_status: "In Stock",
    },
    {
      id: 4,
      imgs: [Img2],
      title: "Mesh Lightweighted Sports, Casual, Outdoor, Model.",
      rating: 2,
      actual_price: "₹700",
      discount_price: "₹350",
      off_percentage: "(50% off)",
      product_status: "In Stock",
    },
    {
      id: 4,
      imgs: [Img2, Img1, Img2],
      title: "Mesh Lightweighted Sports, Casual, Outdoor, Model.",
      rating: 2,
      actual_price: "₹700",
      discount_price: "₹350",
      off_percentage: "(50% off)",
      product_status: "In Stock",
    },
    {
      id: 4,
      imgs: [Img4, Img1, Img2],
      title: "Mesh Lightweighted Sports, Casual, Outdoor, Model.",
      rating: 2,
      actual_price: "₹700",
      discount_price: "₹350",
      off_percentage: "(50% off)",
      product_status: "In Stock",
    },
    {
      id: 4,
      imgs: [Img1, Img1, Img2],
      title: "Mesh Lightweighted Sports, Casual, Outdoor, Model.",
      rating: 2,
      actual_price: "₹700",
      discount_price: "₹350",
      off_percentage: "(50% off)",
      product_status: "In Stock",
    },
    {
      id: 4,
      imgs: [Img3, Img1, Img2],
      title: "Mesh Lightweighted Sports, Casual, Outdoor, Model.",
      rating: 2,
      actual_price: "₹700",
      discount_price: "₹350",
      off_percentage: "(50% off)",
      product_status: "In Stock",
    },
  ],
};
